### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by procedural** [lordio/insanity#6]
The project looks great. How free it is to use? :)

**Comment by lordio** [comment]
Thanks for your interest! I've updated the repo with a LICENSE.md file, using the MIT License. The only requirement is to preserve and redistribute the license file.

A minor caveat: If you use Mods, their implementation should inherit Default::Mod, which refuses automatic tracking (this has to do with Mod's special destruction semantics); any objects created within the Mod should also override IObject's ShouldBeTracked, IsBeingTracked, and SetIsTracked methods similarly (alternatively, you may be able to override the Delete method to call a method of the Mod to handle deletion, but I haven't tested this).

Of course, if you don't use Mods, all other objects should correctly participate in garbage collection.

If you're interested, I've been working on the next generation of this project, which aims to make better use of C++11's new features, including cutting some objects completely (std::thread didn't exist when I started this project!).
